const mongoose = require("mongoose");

const flashcardSchema = new mongoose.Schema(
  {
    // Language (future-ready for more languages)
    language: {
      type: String,
      required: true,
      default: "Japanese"
    },

    // Japanese word (Kanji / Kana)
    word: {
      type: String,
      required: true,
      trim: true
    },

    // Hiragana / Katakana reading
    reading: {
      type: String,
      default: "",
      trim: true
    },

    // English meaning
    meaning: {
      type: String,
      required: true,
      trim: true
    },

    // JLPT Level: N5, N4, N3, N2, N1
    level: {
      type: String,
      enum: ["N5", "N4", "N3", "N2", "N1"],
      required: true
    },

    // Optional grouping (kept for backward compatibility)
    category: {
      type: String,
      default: "basic"
    },

    // How the flashcard was created
    source: {
      type: String,
      enum: ["manual", "jlpt"],
      default: "jlpt"
    },

    // Auto-generated dataset flag
    autoGenerated: {
      type: Boolean,
      default: true
    }
  },
  {
    timestamps: true
  }
);

module.exports = mongoose.model("Flashcard", flashcardSchema);
