const mongoose = require("mongoose");
const fs = require("fs");
const path = require("path");
require("dotenv").config();

const Flashcard = require("../models/Flashcard");

// JLPT levels to import
const levels = ["N5", "N4", "N3", "N2", "N1"];

async function importJLPT() {
  try {
    await mongoose.connect(
      process.env.MONGO_URI || "mongodb://127.0.0.1:27017/linguaplay"
    );

    console.log("✅ MongoDB connected for JLPT import");

    for (const level of levels) {
      const filePath = path.join(__dirname, `../data/jlpt/${level}.json`);

      if (!fs.existsSync(filePath)) {
        console.log(`⚠️ Skipping ${level}: file not found`);
        continue;
      }

      const fileData = fs.readFileSync(filePath, "utf-8");
      const words = JSON.parse(fileData);

      console.log(`🧹 Removing old ${level} JLPT flashcards...`);
      await Flashcard.deleteMany({ level, source: "jlpt" });

      const formatted = words.map(item => ({
        language: "Japanese",
        word: item.word,
        reading: item.reading || "",
        meaning: item.meaning,
        level: item.jlptLevel || level, // ✅ FIX HERE
        source: "jlpt",
        autoGenerated: true
      }));

      console.log(`📦 Importing ${formatted.length} words for ${level}...`);
      await Flashcard.insertMany(formatted);

      console.log(`✅ ${level} import completed`);
    }

    console.log("🎉 ALL JLPT LEVELS IMPORTED SUCCESSFULLY");
    process.exit(0);
  } catch (error) {
    console.error("❌ Import error:", error);
    process.exit(1);
  }
}

importJLPT();
